version: "3.9"

services:
    postgres:
        image: library/postgres:11.4-alpine
        environment:
            POSTGRES_USER: paymentGateway
            POSTGRES_PASSWORD: PaymentGateway123
            POSTGRES_DB: paymentGateway
        ports:
        -   "5432:5432"

    seq:
        image: datalust/seq:2021.1
        environment:
            ACCEPT_EULA: "Y"
        ports:
        -   "5341:5341"
        -   "5342:80"
